CREATE TABLE PA_LOG(
    MDEXM_BNO INT PRIMARY KEY AUTO_INCREMENT,    ## PK (자동증가값)
    MDEXM_YMD TIMESTAMP DEFAULT NOW(),    ## 잔료일자 (기본값 시간형)
    MDEXM_CN VARCHAR(4000) NOT NULL,      ## 진료내용
    MDEXM_CN2 VARCHAR(4000),      ## 처방내용
    MDEXM_QTY INT NOT NULL default 0, 				 ## 처방나간 수량
    USER_NO VARCHAR(20),		## FK임 사용자번호 // USER 테이블의 주키
    DSS_CODE VARCHAR(300), 		## FK임 질병코드 // 질병코드 테이블의 주키
    FOREIGN KEY (USER_NO) REFERENCES USER(USER_NO) ON UPDATE CASCADE,
    FOREIGN KEY (DSS_CODE) REFERENCES USER(DSS_CODE) ON UPDATE CASCADE
); 

CREATE TABLE DSS_INFO(
    DSS_CODE VARCHAR(300) PRIMARY KEY,    ## PK 질병코드 
    DSS_NM VARCHAR(300) NOT NULL ## 질병명
); 